### ISSUE TITLE
New pairing site does not work with old (0.9.5) version

### ISSUE THREAD

**Issue by buzzzo** [openrport/openrport#10]
As per topic, when set the pair_url on the conf and try to add a client I will get an error on the web ui.
Should I upgrade before the rportd bin before add the pairl_url option ?

Thx

**Comment by alhdo** [comment]
HI @buzzzo thank for reporting this. Can you please give some more information. 
0.9.5 is the version of the server or the client. 
If you could post the error message or a screenshot of the error you get. It will be very helpful to find a solution. 

Thanks

**Comment by buzzzo** [comment]
0.9.5 is the version of the server and the version of the web ui.

Now seems to be ok, in the sense that i'm able to download the rport-installer.sh.

Is it normal that ALL the url in the shell file are pointing to the old rport.io site ?

**Comment by buzzzo** [comment]
0.9.5 is the version of the server and the version of the web ui.

Now seems to be ok, in the sense that i'm able to download the rport-installer.sh.

Is it normal that ALL the url in the shell file are pointing to the old rport.io site ?

**Comment by runtimet3rror** [comment]
If you update, It'll update to the newest offical RPort version that will require licence. My suggestion is if pairing still works, to wait for @alhdo to finish development of update script to update to the newest opensource version of rport (0.9.12) then change pairing service.

Also did you use solution from README.md?

We created a new pairing system for running RPort servers. You can use it as follows:

`sudo systemctl stop rportd.service`

Go to line 43-47 in /etc/rport/rportd.conf, change
`pairing_url = "https://pairing.openrport.io"`

Restart the rport server
`sudo systemctl start rportd.service`

**Comment by alhdo** [comment]
The new version of pairing.openrport.io has been updated with the links pointed to openrport.io 
Please upgrade to the latest version
I will close the issue for now. If you get any more trouble please feel free to reopen the issue.
