### ISSUE TITLE
Potential problem upgrading from old releases

### ISSUE THREAD

**Issue by buzzzo** [openrport/openrport#11]
Just a bit of warning.

I've trying to replace the rportd bin (version 0.9.5) both with the one coming from openport fork and neo-rport, resulting in the following problem:

https://github.com/IOTech17/neo-rport/issues/2

I suspect some problem related with sql.

**Comment by mattish91** [comment]
Can confirm, something getting messed up when upgrading from 0.9.5

`Nov 05 23:38:01 rport rportd[9789]: 2023/11/05 23:38:01 failed to init Client Repository: failed to get clients: sql: Scan error on column index 3, name "details": failed to decode 'details' field: json: cannot unmarshal object into Go Scan error on column index 3, name "details": failed to decode 'details' field: json: cannot unmarshal object into Go struct field CommandsConfig.client_configuration.remote_commands.allow_regexp of type *regexp.Regexp`

**Comment by mattish91** [comment]
> Just a bit of warning.
> 
> I've trying to replace the rportd bin (version 0.9.5) both with the one coming from openport fork and neo-rport, resulting in the following problem:
> 
> https://github.com/IOTech17/neo-rport/issues/2
> 
> I suspect some problem related with sql.

Did you ever manage to get it working after that upgrade or did you manage to rollback some how? My rport server can't start any more, i did take multiple backups of both before and after the upgrade but none of them seams to work properly any more.

**Comment by alhdo** [comment]
Can you explain more your situation so we can help you out. What is the version on your clients ?

**Comment by HiFiPhile** [comment]
Hi,

I'm facing the same issue, here is `remote_commands` extracted from `clients.db`:

```
"remote_commands":{"enabled":true,"send_back_limit":4194304,"allow":[".*"],"deny":[],"order":["allow","deny"],"allow_regexp":[{}],"deny_regexp":[]}
```

**Comment by alhdo** [comment]
The solution is to remote the {} inside allow regexp. Or you can clear the details fields in the clients.db.
1- Make a backup of clients.db
```bash
cp clients.db clients.db.back
```
2 - Open sqlite3 and clear the details field
```bash
sqlite3 clients.db
UPDATE clients SET details = '';
```

**Comment by alhdo** [comment]
Please upgrade to the latest release. The issue have been solved.
Please reopen the issue if you get any more issue.

**Comment by innostus** [comment]
I just upgraded from rport 0.9.5 to openrport 0.9.14 on arm64. I ran into this same issue. @alhdo clearing the details fields leaves me with no clients! Any other solutions?

**Comment by HiFiPhile** [comment]
What I did was `UPDATE clients SET details = replace(details, '[{}]', '[]');`

**Comment by innostus** [comment]
Thanks @HiFiPhile , I just figured out a `UPDATE clients SET details = REPLACE(details, '"allow_regexp":[{}]','"allow_regexp":[]');` would do the job. That works!
