### ISSUE TITLE
Cannot update from rport 0.9.5 to openrport 0.9.13 on arm64

### ISSUE THREAD

**Issue by innostus** [openrport/openrport#15]
**Describe the bug**
Cannot update from rport 0.9.5 to openrport 0.9.13 on arm64. 

Trying to update using:
curl -s https://get.openrport.io/update -o rportd-update.sh
sudo -E bash rportd-update.sh

Results in:
[*] Nothing to do. RPortd is on the latest version 0.9.5.

**Environment**
uname -a: Linux rport 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:29:36 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
rportd --version: version 0.9.5

**Additional context**
Does this have anything to do with the fact that there is no arm64 packaged released for linux? How to proceed?

**Comment by alhdo** [comment]
We will be looking into this. Thanks for opening the issues. Indeed there's no build for arm64. We ll try to make a build for Arm64. 

Just for information are you trying to update an instance using a public ip or not ?

**Comment by innostus** [comment]
The server is behind a router. The specific ports for rport are routed directly to the rport server. The http and https ports are router via haproxy to the rport server.

**Comment by JzJad** [comment]
I may have found this a bit late, but attempted the update on arm as well and got the following.

`[*] A backup has been created in /var/backups/rportd-20231016-051921.tar.gz
[*] /usr/local/bin/rportd updated to version version
[*] Performing database migrations where needed.
[*] Reverse Proxy already activated
[*] Monitoring is already enabled.
[*] Frontend updated to 0.9.12-17-build-1145
[*] You are now using RPort Server version (Frontend 0.9.12-17-build-1145)`

Sadly now rportd service crashes and logs give me nothing useful.

**Comment by alhdo** [comment]
A new version with all the bugs fixed are on the way.

**Comment by alhdo** [comment]
A new version with arm64 architecture for rportd has been published. Please upgrade. 
If you get any more issue feel free to reopen the issue. 
I will close it for now.

**Comment by innostus** [comment]
The arm64 package is installable, but not with the rportd-update.sh update script. The script still reports  
[*] Nothing to do. RPortd is on the latest version 0.9.5.
I manually patched the script to download the correct file. This can be installed. However, this results in issue #11

**Comment by alhdo** [comment]
You can check the comment of @HiFile on the upgrade. Please update the client first then you can upgrade the server, should solve the problem. Otherwise let me know. 
I ll update the rport-update.sh to consider arm64 architecture. 
Thank you.

**Comment by HiFiPhile** [comment]
I saw `rport.io` isn't fully cleaned up in update.sh:
https://github.com/openrport/rport-pairing/blob/3082bb54b50886f2b7a9d13981633df9432d53e1/retrieve/templates/linux/update.sh#L94

**Comment by alhdo** [comment]
Good catch. I saw it but wanted to fix the urgent matter first. I will do an update. You can make a PR if you want to. 

Thanks
