### ISSUE TITLE
update problem - link invalid

### ISSUE THREAD

**Issue by rseuster** [openrport/openrport#16]
Hi,
first of all, thanks for picking up the torch for providing a FOSS version of rport !

I am trying to convert from an rport installation to an openrport installation. On one client, trying to update
from rport-0.9.12 to openrport-0.9.13 results in a failure.

I am downloading the update script from openrport.io, but links still point to the rport repositories.
So, fixing those links leads to another problem, namely just replacing rport with openrport in line 637 in the downloaded powershell script
```
$URL  = "https://download.rport.io/rport/$( release )/?arch=Windows_x86_64/&gt=$currentVersion"
```
just delivers a directory listing instead of the package. The install ergo fails. This can be verified by pasting this into a browser, replacing "$( release )" with "stable" and "$currentVersion" with something like "0.9.5"

Also adding "latest.php" right before "?arch" leads to an error.

What is the correct syntax for downloading a file within above framework ?

**Comment by alhdo** [comment]
Hello, 

          Thanks for the support. The installer for windows is not ready yet however the correct link to download it is :
          $URL = "https://download.openrport.io/rport/stable/latest.php?arch=Windows_x86_64"
          
There was a problem with the download server it has been fixed now.

**Comment by alhdo** [comment]
You can reopen the issue if you have any problem related to that.
