### ISSUE TITLE
Can't update 0.9.5 rport server, x86_64 architecture

### ISSUE THREAD

**Issue by etec-masterofsynapse** [openrport/openrport#20]
It looks like I have the same problem as issue #15, however I am on x86_64, and this arch should have builds.
I executed the same commands as in the named issue but the script thinks rport is up-to-date.

**Comment by alhdo** [comment]
Hello @etec-masterofsynapse indeed there was an error in the download server. And it have been solved now. You can give it a try . If you got any issue please open back this issue. 

```bash
curl -s https://get.openrport.io/update -o rportd-update.sh
sudo -E bash rportd-update.sh
```
For more information you can take a look at the docs. 
[Documentation](https://kb.openrport.io/digging-deeper/server-maintenance/updating-rport)

**Comment by etec-masterofsynapse** [comment]
@alhdo I ran the script, it found a new version, but not the 0.9.13 from the repo, but 1.0.1-1-build-1151. After this update to 1.0.1, the frontend doesn't load anymore, HTTP error 502.

**Comment by alhdo** [comment]
The version showed is the fronted version. Can you do a full refresh in your browser and maybe clean the cache to make sure it loads the frontend correctly.

**Comment by etec-masterofsynapse** [comment]
Both versions showed as 1.0.1, frontend and backend.

**Comment by alhdo** [comment]
Okay i will look at the issue and provide a fix. In the meanwhile let me know if the frontend works for you. And test if the api is working also.

**Comment by etec-masterofsynapse** [comment]
I know that the endpoint for the rport clients definitely didn't work, since my monitoring systems picked that up as down, saying "connect ECONNREFUSED x.x.x.x:80".

I also checked the rportd.log, no news in terms of errors, systemctl showed error/stopped.

Most likely, this is caused by the missing license, since realVNC's rport 1.0.1 isn't free anymore.

**Comment by alhdo** [comment]
The update script doesn't have link from rport anymore. Can you jump on the discord server so we can help you figure it out.
