### ISSUE TITLE
Migrate from rport.io to openrport

### ISSUE THREAD

**Issue by kevingarman** [openrport/openrport#22]
First off, thanks for rescuing this excellent tool from realvnc!

I've followed your steps to change the pairing url.  What do I need to do to migrate my server from rport.io 0.9.12 to openrport 0.9.13?

Thanks!

**Comment by JzJad** [comment]
Once you change the pairing url all you have to do is restart the service, once done if you are wanting to update the server you can find that in the docs: https://kb.openrport.io/digging-deeper/server-maintenance/updating-rport

**Comment by kevingarman** [comment]
Well, following those directions for the server upgrade, the `rportd-update.sh` script runs, but now I can't start the rportd service.   

`Nov 09 23:07:36 mon rportd[1037]: 2023/11/09 23:07:36 failed to init Client Repository: failed to get clients: sql: Scan error on column index 3, name "details": failed to decode 'details' field: json: cannot unmarshal object into Go struct field CommandsConfig.client_configuration.remote_commands.allow_regexp of type *regexp.Regexp
Nov 09 23:07:36 mon systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 23:07:36 mon systemd[1]: rportd.service: Failed with result 'exit-code'.
Nov 09 23:09:36 mon systemd[1]: rportd.service: Scheduled restart job, restart counter is at 2.
Nov 09 23:09:36 mon systemd[1]: Stopped Create reverse tunnels with ease..
Nov 09 23:09:36 mon systemd[1]: Started Create reverse tunnels with ease..
Nov 09 23:09:36 mon rportd[1057]: 2023/11/09 23:09:36 failed to init Client Repository: failed to get clients: sql: Scan error on column index 3, name "details": failed to decode 'details' field: json: cannot unmarshal object into Go struct field CommandsConfig.client_configuration.remote_commands.allow_regexp of type *regexp.Regexp
Nov 09 23:09:36 mon systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 23:09:36 mon systemd[1]: rportd.service: Failed with result 'exit-code'.
Nov 09 23:11:36 mon systemd[1]: rportd.service: Scheduled restart job, restart counter is at 3.
Nov 09 23:11:36 mon systemd[1]: Stopped Create reverse tunnels with ease..
Nov 09 23:11:36 mon systemd[1]: Started Create reverse tunnels with ease..
Nov 09 23:11:36 mon rportd[1085]: 2023/11/09 23:11:36 failed to init Client Repository: failed to get clients: sql: Scan error on column index 3, name "details": failed to decode 'details' field: json: cannot unmarshal object into Go struct field CommandsConfig.client_configuration.remote_commands.allow_regexp of type *regexp.Regexp
Nov 09 23:11:36 mon systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 23:11:36 mon systemd[1]: rportd.service: Failed with result 'exit-code'.`

**Comment by kevingarman** [comment]
rportd -v does now show 0.9.13

**Comment by alhdo** [comment]
Here is how to solve this problem while we made a permanent fix.

Connect to the database

```bash
sudo sqlite3 /var/lib/rport/clients.db
```

Updates the clients
```sql
UPDATE clients SET details '';
```

Please close the issue if it fixed it for you. You can come back here if you got any other problems.

**Comment by kevingarman** [comment]
Ya, I came across that on the discourse, but it didn't seem to help....I'll have to try it again.

**Comment by kevingarman** [comment]
...just tried again, and I'm getting the same result after updating the details.

**Comment by kevingarman** [comment]
0.9.14 is working...thanks!
