### ISSUE TITLE
Error on download URL arm64

### ISSUE THREAD

**Issue by Geekmylife** [openrport/openrport#30]
Im getting this on Debian arm64 : 

[-] Downloading https://download.openrport.io/rportd/stable/latest.php?arch=aarch64

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

We are very sorry. Something went wrong.
Command 'tar vxzf rportd.tar.gz -C /usr/local/bin/ rportd' exited erroneous on line 937.

---------------------------------------------
If i open the download link this return : 
{"error":"Invalid architecture"}

**Comment by alhdo** [comment]
The architecture have been added. You can try again now. 

Thanks for reporting this issue.
