### ISSUE TITLE
Latest.php issue

### ISSUE THREAD

**Issue by AivCho123** [openrport/openrport#32]
I saw that Latest.php shows this message {"error":"Missing architecture argument"} in https://download.openrport.io/rport/stable/latest.php

**Comment by JamieMcH** [comment]
Hi @AivCho123
You need to append the arch query to the end.
e.g [https://download.openrport.io/rport/stable/latest.php?arch=windows_x86_64](https://download.openrport.io/rport/stable/latest.php?arch=windows_x86_64)

**Comment by alhdo** [comment]
Thanks @JamieMcH for the answer. If that didn't solve your issue feel free to reopen the issue.
