### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by lagethomas** [openrport/openrport#33]
Don't install rport
![image](https://github.com/openrport/openrport/assets/47001888/e6cf5def-3795-4883-803c-ebb3ca9c53d0)

**Comment by rdeago** [comment]
It works now, as far as I can tell.

**Comment by lagethomas** [comment]
> It works now, as far as I can tell.

He gets paid now, right?

**Comment by alhdo** [comment]
Seems like it is a problem with your local curl. Try to solve that problem and try again. OpenRport is the oss version of the rport. This one is free to use.
