### ISSUE TITLE
rport-installer.ps1 vs rport-installer.sh different tacoscript URLs

### ISSUE THREAD

**Issue by tb-thomas** [openrport/openrport#35]
We tried to deploy openrport the last two days.

At Linux all was fine, but at Windows we got an error while the installer try to download the tacoscript installer.

After checking both installer files we saw that the Linux installer download tacoscript from here "https://download.rport.io/tacoscript/${RELEASE}/?arch=Linux_${ARCH}"
The windows installer try to download from here "https://download.openrport.io/tacoscript/$( $release )/?arch=Windows_x86_64"

It looks like that the at opnrport.io the download doesn't work as expected, because this website is downloaded "https://download.openrport.io/tacoscript/stable/" and stored as tacoscript.zip

If you change the URL to download.rport.io or to a direct download it is working.

**Comment by alhdo** [comment]
Thank you @tb-thomas  for reporting this issue. We will publish a fix.

**Comment by alhdo** [comment]
A fix has been published for this issue. Please re-open the issue if it doesn't works for you.
