### ISSUE TITLE
error when updating client version using script

### ISSUE THREAD

**Issue by ebym** [openrport/openrport#36]
**Describe the bug**
Not sure if this is a bug or should be in Discussions, but affects  linux clients and not tested on Windows clients.

rport clients(0.9.12) are installed with sudo rights `sh rport-installer.sh -x -s -r -b -i`

When trying to update rport clients to latest version using script provided here "[https://kb.openrport.io/digging-deeper/server-maintenance/updating-rport](https://kb.openrport.io/digging-deeper/server-maintenance/updating-rport)" using scripts from rport server, client system download `rport-update.sh` to /tmp/ and does nothing. Further investigation of `rport-update.log` reveal the update script should be executed as root or using sudo. 

rport clients are already installed with sudo rights, shouldn't it execute without sudo ?.

When update script is manually executed, the client is updated and show version 1.0.3.

`sudo sh /tmp/rport-update.sh >/tmp/rport-update.log 2>&1`

**Environment**
* RPortd version: 0.9.12 - Ubuntu 22.04 LTS.
* RPort version : 0.9.12
* Client OS details : Ubuntu 22.04 LTS, Ubuntu 18.04 LTS
* Is rportd running inside a docker container? : Native Installation.
* Are you using a reverse proxy? If yes, which one? : No reverse proxy.

**Log file**
cat /tmp/rport-update.log 
/tmp/rport-update.sh: 739: /tmp/rport-update.sh: /usr/local/bin/rport: not found
Execute as root or use sudo. Exit!

An error occurred.
Try running in debug mode with 'sh -x /tmp/rport-update.sh '
Ask for help on https://github.com/openrport/openrport-pairing/discussions/categories/help-needed 

Thanks,

**Comment by alhdo** [comment]
Hello, 

      First you need to run the script with sudo. Even if you installed it with sudo. The rport executable doesn't have sudo rights. When doing the script to update you are not using rport binary but the script itself.
      
      Let me know if your problem have been solved. Feel free to reopen the issue if your problem is not solved.
