### ISSUE TITLE
Status Update Request on OpenRPort Project

### ISSUE THREAD

**Issue by mcazautet** [openrport/openrport#43]
Hello OpenRPort Team,

I've been following the OpenRPort project with great interest, especially given its relevance to security. Noticed there hasn't been activity for 3 months. Is the project still being actively developed? Understanding the project's status is crucial due to its security implications. Any updates would be greatly appreciated.

Thanks

**Comment by alhdo** [comment]
Hello @mcazautet, 

          Thanks for reaching out, we are still under active development, we are mainly focus on developing a new front-end to be really independent from RPort closed source. For now we are limited individual trying to make this work. We will keep pushing new and incremental change. Thanks for your support you can donate to the project so the team member will be able to spend more time on it. If you are a dev you can join the project and do some PR. 
          
          You can join the discord to get more up to date news. 
          
          Thank you.

**Comment by mcazautet** [comment]
Hello @alhdo,

thanks for the update on the project's progress. We're interested in possibly supporting OpenRPort through development contributions, particularly with the new frontend. However, we couldn't find the repository for this frontend. Could you direct us to where we might find it or how to get involved? We're evaluating our capacity to contribute and would appreciate more information on how we can help, should we decide to proceed.

Best regards, Maurice

**Comment by alhdo** [comment]
Now the repository is private because it is not yet ready we will make it public once we have a usable version. If you are interested i can add you to the private repository so you can have a look.

**Comment by mcazautet** [comment]
Thanks for the offer! You can gladly add me to the private repository so I can review the toolstack and see if we can help.

**Comment by alhdo** [comment]
I will add you to the repository and for information. The technology is Nuxt 3 based on vuejs.

**Comment by mcazautet** [comment]
@alhdo friendly reminder.

**Comment by mcazautet** [comment]
@alhdo 

The invitation didn't come through. Could you send it again? Thanks 😃

**Comment by alhdo** [comment]
Done. Please join the discord server for a discussion
