### ISSUE TITLE
following with great interest. what about private pairing servers?

### ISSUE THREAD

**Issue by adtech-scott** [openrport/openrport#44]
one of the things that always bothered me about rport was it's reliance on the rport.io pairing server.
is there a reason that openrport could not allow us to run our own pairing servers?

**Comment by adtech-scott** [comment]
my bad... i did not see that the pairing service was a separate project.

sweet, i'm going to start testing

**Comment by alhdo** [comment]
Thanks @adtech-scott i will close the issue. Please re open an issue if you have any problem with that.
