### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Heggeg** [openrport/openrport#46]
Hi, 
is it possible to deploy openrport via docker? 

I currently still have rport running but it bothers me that I had to install it natively. 

I love rport and want to switch to openrport. Since the paywall for rport came, rport has been running unused on my network. I would like to change that and install openrport and migrate my clients. 

Thank you so far :)

**Comment by alhdo** [comment]
Hello @Heggeg you can find on github some repo who did the docker file for rport it will still work with openrport. If the community is interested i will do an official image. Thanks you. I will add it on the roadmap anyway.

**Comment by archef2000** [comment]
Would you accept a PR for it?
