### ISSUE TITLE
Pairing service not working

### ISSUE THREAD

**Issue by renatomb** [openrport/openrport#49]
When I click on install client, there is no script on the page with the commands to run on windows/linux.

<img width="663" alt="rport-no-pairing" src="https://github.com/openrport/openrport/assets/30217311/603240ca-0953-42be-aac8-8a755b0a6f85">

Not using a custom pairing service, just the default, is it working?

**Comment by msbusk** [comment]
It seems that the http://openrport.io/ site is down which hosts the pairing service; we can neither install any clients nor update existing clients.

**Comment by alhdo** [comment]
I will close this issue as this problem have been solved.
